version: '3.7'

services:
  app:
    image: 'buftio'
    container_name: buftio

    build:
      context: .
      dockerfile: Dockerfile
      target: deploy-node

    restart: unless-stopped

networks:
  default:
    name: server-private
    external: true
